#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Feb 12, 2019 02:16:20 PM +0545  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Login_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel_Login (root)
    Login_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel_Login(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel_Login (w)
    Login_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel_Login():
    global w
    w.destroy()
    w = None

class Toplevel_Login:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font9 = "-family {Sitka Heading} -size 20 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("351x304+477+130")
        top.title("Parking Management : Login")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Labelframe_login = tk.LabelFrame(top)
        self.Labelframe_login.place(relx=0.028, rely=0.033, relheight=0.938
                , relwidth=0.94)
        self.Labelframe_login.configure(relief='groove')
        self.Labelframe_login.configure(foreground="black")
        self.Labelframe_login.configure(text='''Login : Parking Management''')
        self.Labelframe_login.configure(background="#d9d9d9")
        self.Labelframe_login.configure(highlightbackground="#d9d9d9")
        self.Labelframe_login.configure(highlightcolor="black")
        self.Labelframe_login.configure(width=330)

        self.Label_login_username = tk.Label(self.Labelframe_login)
        self.Label_login_username.place(relx=0.061, rely=0.175, height=21
                , width=65, bordermode='ignore')
        self.Label_login_username.configure(activebackground="#f9f9f9")
        self.Label_login_username.configure(activeforeground="black")
        self.Label_login_username.configure(background="#d9d9d9")
        self.Label_login_username.configure(disabledforeground="#a3a3a3")
        self.Label_login_username.configure(foreground="#000000")
        self.Label_login_username.configure(highlightbackground="#d9d9d9")
        self.Label_login_username.configure(highlightcolor="black")
        self.Label_login_username.configure(text='''Username :''')

        self.Label_Login_Password = tk.Label(self.Labelframe_login)
        self.Label_Login_Password.place(relx=0.061, rely=0.316, height=21
                , width=62, bordermode='ignore')
        self.Label_Login_Password.configure(activebackground="#f9f9f9")
        self.Label_Login_Password.configure(activeforeground="black")
        self.Label_Login_Password.configure(background="#d9d9d9")
        self.Label_Login_Password.configure(disabledforeground="#a3a3a3")
        self.Label_Login_Password.configure(foreground="#000000")
        self.Label_Login_Password.configure(highlightbackground="#d9d9d9")
        self.Label_Login_Password.configure(highlightcolor="black")
        self.Label_Login_Password.configure(text='''Password :''')

        self.Entry_Login_Username = tk.Entry(self.Labelframe_login)
        self.Entry_Login_Username.place(relx=0.273, rely=0.175, height=20
                , relwidth=0.679, bordermode='ignore')
        self.Entry_Login_Username.configure(background="white")
        self.Entry_Login_Username.configure(disabledforeground="#a3a3a3")
        self.Entry_Login_Username.configure(font="TkFixedFont")
        self.Entry_Login_Username.configure(foreground="#000000")
        self.Entry_Login_Username.configure(highlightbackground="#d9d9d9")
        self.Entry_Login_Username.configure(highlightcolor="black")
        self.Entry_Login_Username.configure(insertbackground="black")
        self.Entry_Login_Username.configure(selectbackground="#c4c4c4")
        self.Entry_Login_Username.configure(selectforeground="black")

        self.Entry_Login_Password = tk.Entry(self.Labelframe_login)
        self.Entry_Login_Password.place(relx=0.273, rely=0.316, height=20
                , relwidth=0.679, bordermode='ignore')
        self.Entry_Login_Password.configure(background="white")
        self.Entry_Login_Password.configure(disabledforeground="#a3a3a3")
        self.Entry_Login_Password.configure(font="TkFixedFont")
        self.Entry_Login_Password.configure(foreground="#000000")
        self.Entry_Login_Password.configure(highlightbackground="#d9d9d9")
        self.Entry_Login_Password.configure(highlightcolor="black")
        self.Entry_Login_Password.configure(insertbackground="black")
        self.Entry_Login_Password.configure(selectbackground="#c4c4c4")
        self.Entry_Login_Password.configure(selectforeground="black")

        self.Button_Login_Cancel = tk.Button(self.Labelframe_login)
        self.Button_Login_Cancel.place(relx=0.303, rely=0.491, height=24
                , width=67, bordermode='ignore')
        self.Button_Login_Cancel.configure(activebackground="#ececec")
        self.Button_Login_Cancel.configure(activeforeground="#000000")
        self.Button_Login_Cancel.configure(background="#d9d9d9")
        self.Button_Login_Cancel.configure(disabledforeground="#a3a3a3")
        self.Button_Login_Cancel.configure(foreground="#000000")
        self.Button_Login_Cancel.configure(highlightbackground="#d9d9d9")
        self.Button_Login_Cancel.configure(highlightcolor="black")
        self.Button_Login_Cancel.configure(pady="0")
        self.Button_Login_Cancel.configure(text='''Cancel''')

        self.Button_Login_Login = tk.Button(self.Labelframe_login)
        self.Button_Login_Login.place(relx=0.576, rely=0.491, height=24
                , width=121, bordermode='ignore')
        self.Button_Login_Login.configure(activebackground="#ececec")
        self.Button_Login_Login.configure(activeforeground="#000000")
        self.Button_Login_Login.configure(background="#d9d9d9")
        self.Button_Login_Login.configure(disabledforeground="#a3a3a3")
        self.Button_Login_Login.configure(foreground="#000000")
        self.Button_Login_Login.configure(highlightbackground="#d9d9d9")
        self.Button_Login_Login.configure(highlightcolor="black")
        self.Button_Login_Login.configure(pady="0")
        self.Button_Login_Login.configure(text='''Login''')

        self.Message_Login_Title = tk.Message(self.Labelframe_login)
        self.Message_Login_Title.place(relx=0.03, rely=0.632, relheight=0.298
                , relwidth=0.945, bordermode='ignore')
        self.Message_Login_Title.configure(background="#d9d9d9")
        self.Message_Login_Title.configure(font=font9)
        self.Message_Login_Title.configure(foreground="#000000")
        self.Message_Login_Title.configure(highlightbackground="#d9d9d9")
        self.Message_Login_Title.configure(highlightcolor="black")
        self.Message_Login_Title.configure(justify='center')
        self.Message_Login_Title.configure(text='''Parking Management''')
        self.Message_Login_Title.configure(width=312)

if __name__ == '__main__':
    vp_start_gui()





