#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Feb 12, 2019 02:36:48 PM +0545  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import mainwindow_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Window_Parking_Management (root)
    mainwindow_support.init(root, top)
    root.mainloop()

w = None
def create_Window_Parking_Management(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Window_Parking_Management (w)
    mainwindow_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Window_Parking_Management():
    global w
    w.destroy()
    w = None

class Window_Parking_Management:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font9 = "-family {Bahnschrift SemiBold} -size 40 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"

        top.geometry("1366x715+364+141")
        top.title("Parking Management")
        top.configure(background="#d9d9d9")

        self.Label_PM_title = tk.Label(top)
        self.Label_PM_title.place(relx=-0.015, rely=0.0, height=70, width=543)
        self.Label_PM_title.configure(background="#d9d9d9")
        self.Label_PM_title.configure(disabledforeground="#a3a3a3")
        self.Label_PM_title.configure(font=font9)
        self.Label_PM_title.configure(foreground="#000000")
        self.Label_PM_title.configure(text='''Parking Management''')
        self.Label_PM_title.configure(width=543)

        self.Frame_Video = tk.Frame(top)
        self.Frame_Video.place(relx=0.505, rely=0.098, relheight=0.888
                , relwidth=0.487)
        self.Frame_Video.configure(relief='groove')
        self.Frame_Video.configure(borderwidth="2")
        self.Frame_Video.configure(relief='groove')
        self.Frame_Video.configure(background="#d9d9d9")
        self.Frame_Video.configure(width=665)

        self.Frame_Info = tk.Frame(top)
        self.Frame_Info.place(relx=0.007, rely=0.098, relheight=0.888
                , relwidth=0.487)
        self.Frame_Info.configure(relief='groove')
        self.Frame_Info.configure(borderwidth="2")
        self.Frame_Info.configure(relief='groove')
        self.Frame_Info.configure(background="#d9d9d9")
        self.Frame_Info.configure(width=665)

if __name__ == '__main__':
    vp_start_gui()





